### ISSUE TITLE
Failed setup; will retry : 'HostName'

### ISSUE THREAD

**Issue by Xornop** [mversluijs/homeassistant_nokiaxs2426gb_devicetracker#3]
After install with HACS, I set it up via integrations in the UI. Then I get the error in the title.

Relevant error log:

> 
> > 
> 2024-11-14 14:44:48.481 DEBUG (SyncWorker_5) [custom_components.nokiaxs2426gb.nokia] POST http://192.168.69.1/login_web_app.cgi?nonce
> 2024-11-14 14:44:48.481 DEBUG (SyncWorker_5) [custom_components.nokiaxs2426gb.nokia] response status: 200
> 2024-11-14 14:44:48.941 DEBUG (SyncWorker_5) [custom_components.nokiaxs2426gb.nokia] logged in succesfully
> 2024-11-14 14:44:49.091 DEBUG (SyncWorker_5) [custom_components.nokiaxs2426gb.nokia] logged in? Yes
> 2024-11-14 14:44:49.282 DEBUG (SyncWorker_5) [custom_components.nokiaxs2426gb.router] Nokia track_devices = 'True', device mode '0'
> 2024-11-14 14:44:49.429 DEBUG (SyncWorker_8) [custom_components.nokiaxs2426gb.nokia] logged in? Yes
> 2024-11-14 14:44:51.817 DEBUG (SyncWorker_8) [custom_components.nokiaxs2426gb.nokia] GET http://192.168.69.1/lan_status_web_app.cgi?wlan
> 2024-11-14 14:44:51.817 DEBUG (SyncWorker_8) [custom_components.nokiaxs2426gb.nokia] response status: 200
> 2024-11-14 14:44:51.818 INFO (SyncWorker_8) [custom_components.nokiaxs2426gb.nokia] Got 10 devices
> 2024-11-14 14:44:51.820 ERROR (MainThread) [custom_components.nokiaxs2426gb] Unexpected error fetching Nokia router Devices data
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
>     return await self.update_method()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nokiaxs2426gb/__init__.py", line 59, in async_update_devices
>     return await router.async_update_device_trackers()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nokiaxs2426gb/router.py", line 170, in async_update_device_trackers
>     ntg_devices = await self.async_get_attached_devices()
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nokiaxs2426gb/router.py", line 163, in async_get_attached_devices
>     return await self.hass.async_add_executor_job(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nokiaxs2426gb/nokia.py", line 272, in get_attached_devices
>     name = line['HostName']
>            ~~~~^^^^^^^^^^^^
> KeyError: 'HostName'
> 2024-11-14 14:44:51.823 DEBUG (MainThread) [custom_components.nokiaxs2426gb] Finished fetching Nokia router Devices data in 2.540 seconds (success: False)

**Comment by ReneWassinkAlliander** [comment]
The problem here is, that the HostName variable is not in the JSON part where it is expected. The hostname might even be empty, so the quickest (and also maybe dirtiest) fix is to set the name variable to the IP address. See attached nokia.py file. After this change, the entries popped up in Home Assistant.

Remember to rename nokia.txt to nokia,py, and restart Home Assistant after updating the file.
[nokia.txt](https://github.com/user-attachments/files/18280925/nokia.txt)

(I don't know what the preferred way is to handle a change like this; this way you at least have all the info)

**Comment by mversluijs** [comment]
@Xornop, @ReneWassinkAlliander, thanks for pointing out this issue. This should be fixed with [this](https://github.com/mversluijs/homeassistant_nokiaxs2426gb_devicetracker/commit/08de7b15187d0d8f68ece20c80cb210293d5b935) commit in the latest version.
